### ISSUE TITLE
Armor slots bug.

### ISSUE THREAD

**Issue by andris155** [Lyxnx/ChestShop-5#2]
1. Buy items chestshop
2. inventory full
3. chestshop placed item Armor slots
![3c754f5c-1aaf-11e6-9cc4-b4723bfae0d1](https://cloud.githubusercontent.com/assets/8324198/15274579/cc01bad8-1ab5-11e6-931d-1dbfa65a46e9.png)

**Comment by Lyxnx** [comment]
This is the old version you are using. This repository is for the new rewrite which will attempt to fix everything.

**Comment by andris155** [comment]
I used ChestShop4.0-r5 this is latest version. (?)

**Comment by Lyxnx** [comment]
r5 is the latest version available, yes, but this repo is for the new 5.0 rewrite.
